### ISSUE TITLE
Filter by FROM or LABEL

### ISSUE THREAD

**Issue by alexauvray** [Battleman/PyMailExtract#2]
Would you know what to add in your script to filter only messages with a certain FROM or LABEL ? I tried looking in the Google API Doc but I keep getting errors...

**Comment by Battleman** [comment]
For that, you want to call `get_messages_list` and provide a parameter to `query`.
For example,

    token, mails_list = get_messages_list(token=token, query="from:someuser@example.com", service=service)

Example query [provided by google](https://developers.google.com/gmail/api/v1/reference/users/messages/list): `"from:someuser@example.com rfc822msgid:<somemsgid@example.com> is:unread"`
